version: '3'

services:
  
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=nexttodo_app
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3309:3306
    expose:
      - 3309
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
